openapi: 3.0.3
info:
  title: DjangoVue API
  version: 1.0.0
paths:
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
        '401':
          content:
            application/vnd.oai.openapi:
              schema:
                $ref: '#/components/schemas/UnauthenticatedError'
            application/yaml:
              schema:
                $ref: '#/components/schemas/UnauthenticatedError'
            application/vnd.oai.openapi+json:
              schema:
                $ref: '#/components/schemas/UnauthenticatedError'
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthenticatedError'
          description: ''
        '403':
          content:
            application/vnd.oai.openapi:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
            application/yaml:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
            application/vnd.oai.openapi+json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
          description: ''
components:
  schemas:
    ErrorDetail:
      type: object
      properties:
        code:
          type: string
          description: An error code linked to a specific error.
        detail:
          type: string
          description: A verbose error message to show to the user.
        attr:
          type: string
          description: The field the error relates to.
      required:
      - attr
      - code
      - detail
    ForbiddenError:
      type: object
      properties:
        type:
          type: string
          default: client_error
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDetail'
          description: A list errors.
      required:
      - errors
    NotFoundError:
      type: object
      properties:
        type:
          type: string
          default: client_error
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDetail'
          description: A list errors.
      required:
      - errors
    UnauthenticatedError:
      type: object
      properties:
        type:
          type: string
          default: client_error
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDetail'
          description: A list errors.
      required:
      - errors
    ValidationError:
      type: object
      properties:
        type:
          type: string
          default: validation_error
          description: Type of error
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDetail'
          description: A list errors.
      required:
      - errors
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
