/* tslint:disable */
/* eslint-disable */
/**
 * DjangoVue API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorDetail } from './ErrorDetail';
import {
    ErrorDetailFromJSON,
    ErrorDetailFromJSONTyped,
    ErrorDetailToJSON,
    ErrorDetailToJSONTyped,
} from './ErrorDetail';

/**
 * 
 * @export
 * @interface ForbiddenError
 */
export interface ForbiddenError {
    /**
     * 
     * @type {string}
     * @memberof ForbiddenError
     */
    type?: string;
    /**
     * A list errors.
     * @type {Array<ErrorDetail>}
     * @memberof ForbiddenError
     */
    errors: Array<ErrorDetail>;
}

/**
 * Check if a given object implements the ForbiddenError interface.
 */
export function instanceOfForbiddenError(value: object): value is ForbiddenError {
    if (!('errors' in value) || value['errors'] === undefined) return false;
    return true;
}

export function ForbiddenErrorFromJSON(json: any): ForbiddenError {
    return ForbiddenErrorFromJSONTyped(json, false);
}

export function ForbiddenErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForbiddenError {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'errors': ((json['errors'] as Array<any>).map(ErrorDetailFromJSON)),
    };
}

export function ForbiddenErrorToJSON(json: any): ForbiddenError {
    return ForbiddenErrorToJSONTyped(json, false);
}

export function ForbiddenErrorToJSONTyped(value?: ForbiddenError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'errors': ((value['errors'] as Array<any>).map(ErrorDetailToJSON)),
    };
}

